name: Weekly Digest Automation

on:
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:

jobs:
  generate-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Digest Script
        run: node scripts/generateDigest.js

      - name: Upload Digest Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: digests/weekly.md

      - name: Upload to Supabase Storage (optional)
        if: ${{ secrets.SUPABASE_URL && secrets.SUPABASE_SERVICE_ROLE_KEY && secrets.SUPABASE_BUCKET }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
        run: |
          set -e
          curl -sS -X POST "$SUPABASE_URL/storage/v1/object/$SUPABASE_BUCKET/digests/weekly.md" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: text/markdown" \
            --data-binary @digests/weekly.md \
            -o /dev/null -w "%{http_code}\n"
