name: QR Scan Heatmap Update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch Scan Data
        run: node scripts/fetchQRScans.js

      - name: Generate Heatmap
        run: node scripts/generateHeatmap.js

      - name: Commit Heatmap
        run: |
          git config --global user.name "NXConner"
          git config --global user.email "nxconner@users.noreply.github.com"
          git add data/qrScans.json public/heatmapOverlay.json
          git commit -m "Update heatmap overlay [skip ci]" || echo "No changes to commit"
          git push
