'use strict';

const fs = require('fs');
const path = require('path');
const digestPath = path.join(__dirname, '..', 'digests', 'weekly.md');

function generateDigest() {
  const timestamp = new Date().toISOString();
  const digest = `

🗓️ Weekly Digest – ${timestamp}

🚀 Deployment Updates
- Modules synced across 12 states
- QR scan heat zones updated
- Crew leaderboard refreshed

📊 Enhancement Logs
- EXE/APK packaging optimized
- Supabase webhook triggers refined
- Public dashboard syndication expanded

🔗 Syndication Channels
- Microsite, press room, investor dashboard live

---

Generated by FieldOpsSuite CI/CD
`;

  fs.writeFileSync(digestPath, digest, 'utf8');
  console.log('✅ Weekly digest generated');
}

generateDigest();

